let circleOrganization = {
    name:"Tech karo",
    purpose:"Women Empowerment",
    passedCohort:1,
    startingYear:2018,
    currentCohort:"second",
    syllabus:["HTML", "CSS", "Java Script"],
    curriculumResources:["Videos", "Books", "Quizes", "Lectures"],
    references:"tutorials",
    currentGropus:2,
    groupsName:["A", "B"],
    certification:"FreeCodeCamp",
    passedGraduates:100,
    employedStudents:67,
    events:["Female Shadowing Class", "Elevate Programme", "Girls Take Charge"],
    lifeSkill:"Self Grooming Program",
    lifeSkillsTopics:["CV Writing","Effective Communication", "Presentation Stratigies", "Problem Solving", "Discipline Mangement"],
    speakersOfLifeSkill:[
        {
            name:"Sir Tahir",
            topicCovered:["CV Writing", "Effective Communication"],
            instituteName:"Amwajj",
            contactNumber:"0456-3456789",
            designation:"Motivational Speaker"
        },
        {
            name:"Sir Mansoor",
            topicCovered:"Effective Communication",
            instituteName:"Amwajj",
            contactNumber:"0345-3488789",
            designation:"Motivational Speaker" 
        },
        {
            name:"Sir Ammar",
            topicCovered:"Presentation Stratigies",
            instituteName:"The School of Leadership",
            contactNumber:"0456-5678432",
            designation:"Motivational Speaker"
        },
        {
            name:"Sir Jawwad",
            topicCovered:"Problem Solving",
            instituteName:"The School of Leadership",
            contactNumber:"0345-5438411",
            designation:"Motivational Speaker" 
        },
        {
            name:"Miss Maham",
            topicCovered:"Discipline Management",
            instituteName:"The School of Leadership",
            contactNumber:"0346-54383210",
            designation:"Motivational Speaker" 
        }
    ],
    mentorMeetup:"Last Saturday of Each Month",
    timingForMentorMeetup:"3 hours",
    mentorsData:[
        {
            name:"Saeed",
            fromInstitute:"10 Pearls",
            contactNumber:"0345-8009765",
            dateOfJoining:"12 Dec,2018",
            isTechKaroStudent:true,
            package:20000,
            lastPackage:8000,
            previousProfession:"Teacher",
            isHappy:true,
            qualification:"F.A"
        },
        {
            name:"Taliya",
            fromInstitute:"Susta Ticket",
            contactNumber:"0345-8009789",
            dateOfJoining:"12 January,2018",
            isTechKaroStudent:false,
            package:25000,
            lastPackage:20000,
            previousProfession:"Supervisor",
            isHappy:true,
            qualification:"Web Developer"
        },
        {
            name:"Sarah",
            fromInstitute:"Amazon",
            contactNumber:"0345-8789656",
            dateOfJoining:"14th Feb,2017",
            isTechKaroStudent:true,
            package:40000,
            lastPackage:20000,
            previousProfession:"Teacher",
            isHappy:true,
            qualification:"Web Designer"
        },
        {
            name:"Saleha",
            fromInstitute:"10 Pearls",
            contactNumber:"0345-8009897",
            dateOfJoining:"1st March,2013",
            isTechKaroStudent:false,
            package:35000,
            lastPackage:8000,
            previousProfession:"Teacher",
            isHappy:true,
            qualification:"Web Developer"
        },
        {
            name:"Kinza",
            fromInstitute:"10 Pearls",
            contactNumber:"0300-1079765",
            dateOfJoining:"4th April,2018",
            isTechKaroStudent:true,
            package:35000,
            lastPackage:12000,
            previousProfession:"Teacher",
            isHappy:true,
            qualification:"Web Developer (Full Stack)"
        },
        {
            name:"Akmal",
            fromInstitute:"10 Pearls",
            contactNumber:"0300-1890765",
            dateOfJoining:"4th August,2018",
            isTechKaroStudent:true,
            package:55000,
            lastPackage:20000,
            previousProfession:"Designer",
            isHappy:true,
            qualification:"Web Developer (Back end)" 
        },
        {
            name:"Falak",
            fromInstitute:"Amazon",
            contactNumber:"0346-1220705",
            dateOfJoining:"30th August,2018",
            isTechKaroStudent:true,
            package:40000,
            lastPackage:12000,
            previousProfession:"Teacher",
            isHappy:true,
            qualification:"Web Developer (Back end)" 
        }
    ],
    founder:"Miss Sadaffe",
    faculty:[
        {
            name:"Miss Sarah",
            designation:"Teacher",
            qualification:"Web Developer",
            contactNumber:"0346-2009876",
            institution:"NED University",
            dateOfJoining:"20th April,2017",
            gender:"Female"
        },
        {
            name:"Miss Tooba",
            designation:"Program Manager",
            qualification:"Web Developer",
            contactNumber:"0346-2009077",
            institution:"NED University",
            dateOfJoining:"28th March,2017",
            gender:"Female"
        },
        {
            name:"Miss Mashaal",
            designation:"Program Director",
            qualification:"Web Developer",
            contactNumber:"0346-6759027",
            institution:"NED University",
            dateOfJoining:"1st January,2015",
            gender:"female"
        },
        {
            name:"Miss Misbah",
            designation:"Program Director",
            qualification:"Web Developer",
            contactNumber:"0333-7894562",
            institution:"NED University",
            dateOfJoining:"21st June,2019",
            gender:"Female"
        },
        {
            name:"Miss Moiza",
            designation:"Admin",
            qualification:"Web Developer",
            contactNumber:"0346-6759027",
            institution:"Karachi University",
            dateOfJoining:"3rd February,2016",
            gender:"Female"
        },
        {
            name:"Miss Mishaal",
            designation:"Program Director",
            qualification:"Web Developer",
            contactNumber:"0336-2198769",
            institution:"NED University",
            dateOfJoining:"4th April,2012",
            gender:"Female"
        },
        {
            name:"Miss Maida",
            designation:"Program Manager",
            qualification:"Web Developer",
            contactNumber:"0300-2331460",
            institution:"NED University",
            dateOfJoining:"18th October,2014",
            gender:"Female"
        },
        {
            name:"Miss Maham",
            designation:"Program Director",
            qualification:"Web Developer",
            contactNumber:"0336-1123456",
            institution:"Mehran University",
            dateOfJoining:"4th April,2018",
            gender:"Female"
        }
    ],
    techNinjas:[
        {
            name:"Miss Kher-un-Nisa",
            qualification:"Web Developer",
            dateOfJoining:"12th Dec,2018",
            institutionName:"NED Unoversity",
            contactNumber:"0216-4456789",
            gender:"Female"
        },
        {
            name:"Miss Rabia",
            qualification:"Web Developer",
            dateOfJoining:"12th Nov,2018",
            institutionName:"NED Unoversity",
            contactNumber:"0216-4457771",
            gender:"Female"
        },
        {
            name:"Miss Noreen",
            qualification:"Web Developer",
            dateOfJoining:"12th Dec,2018",
            institutionName:"NED Unoversity",
            contactNumber:"0216-4456789",
            gender:"Female"
        },
        {
            name:"Mr. Ali",
            qualification:"Web Developer",
            dateOfJoining:"18th Jan,2018",
            institutionName:"Karachi University",
            contactNumber:"0346-6765789",
            gender:"Male"
        },
        {
            name:"Mr. Tofique",
            qualification:"Web Developer",
            dateOfJoining:"12th May,2017",
            institutionName:"NED Unoversity",
            contactNumber:"0345-4456789",
            gender:"Male"
        },
        {
            name:"Mr. Salman",
            qualification:"Web Developer",
            dateOfJoining:"2nd Feb,2018",
            institutionName:"NED Unoversity",
            contactNumber:"0333-67890541",
            gender:"Male"
        },
        {
            name:"Abeera",
            qualification:"Web Developer",
            dateOfJoining:"12th May,2019",
            institutionName:"Aptech",
            contactNumber:"0346-7676760",
            gender:"Female"
        },
        {
            name:"Miss Taliya",
            qualification:"Web Developer",
            dateOfJoining:"8th March,2017",
            institutionName:"NED Unoversity",
            contactNumber:"0346-9876543",
            gender:"Female"
        },
        {
            name:"Miss Asma",
            qualification:"Soft Wear Engineer",
            dateOfJoining:"18th September,2018",
            institutionName:"NED Unoversity",
            contactNumber:"0321-6576563",
            gender:"Female"
        },
        {
            name:"Miss Rehmania",
            qualification:"Soft Wear Engineer",
            dateOfJoining:"18th August,2018",
            institutionName:"NED Unoversity",
            contactNumber:"0321-65754321",
            gender:"Female" 
        },
        {
            name:"Mr. Danish",
            qualification:"Web Developer",
            dateOfJoining:"21st Dec 2016",
            institutionName:"NED Unoversity",
            contactNumber:"0333-67890541",
            gender:"Male"
        },
        {
            name:"Mr. Raza",
            qualification:"Web Developer",
            dateOfJoining:"22nd January,2017",
            institutionName:"NED Unoversity",
            contactNumber:"0300-6786021",
            gender:"Male" 
        },
        {
            name:"Mr. Yahya",
            qualification:"Web Developer",
            dateOfJoining:"21st Dec 2016",
            institutionName:"Orasof",
            contactNumber:"0333-8796453",
            gender:"Male"
        },
        {
            name:"Miss Saleha",
            qualification:"Web Developer",
            dateOfJoining:"23rd July 2017",
            institutionName:"Usman Institute Of Technology",
            contactNumber:"0300-3456789",
            gender:"Female" 
        }
    ],
    isProgress:"true",
    fees:500,
    isFeesLess:true,
    standardOfEducation:"high",
    isScholarshipOffers:true,
    durationOfCourse:"8 months",
    classConduction:"3 days weekly",
    classDuration:"4 hours",
    staticSite:"Usman Institute Of Technology",
    addressOfInstitute:"University Road Near Safari Park",
    isInternshipOffers:true,
    investmentMonthly:"1,50000",
    vehicleExpense:12000,
    classExpense:10000,
    computerExpense:30000,
    electricExpense:10000,
    otherExpenses:50000,
    investmentYearly:"16,00000",
    isExtraClass:true,
    sponsors:[
        {
            name:"Engro Vopak",
            amount:12345,
        },
        {
            name:"HBL",
            amount:3456,
        },
        {
            name:"Sasta Ticket",
            amount:9890,
        }
    ],
    collaborations:["HBL", "First Women Bank", "Mitsubishi", "Sasta ticket", "Engro Vopak", "UBL", "TCF"],
    courseTitle:"Web Development",
    supportingStaff:10,
    curriculumDesigner:"Mashood Rasgher",
    affiliation:["University Of Karachi", "Higher Education Commission"],
    maleStudent:30,
    femaleStudent:70,
    currentStrength: currentStrength
};

let currentStrength = [
    {
        name:"Aisha",
        contactNumber:"0333-8009665",
        education:"Bachelor of Science",
        hasPromoCode:true,
        group:"B",
        hobbies:["Drawing", "Coding"],
        age:201,
        isHappy:true,
        height:4,
        cnic:"41204-445687-9",
        email:"aishakeh3@gmail.com",
        gender:"female",
        address:"Baldia Town",
        isEmployed:true,
        fatherName:"Muhammad Ahmed",
        fatherIncome:30000,
        maritalStatus:"Single",
        siblings:4,
        isComingFromJob:true
    },
    {
        name:"Sameer",
        contactNumber:"0333-5007889",
        education:"F.Sc",
        hasPromoCode:true,
        group:"A",
        hobbies:["Riding", "Singing"],
        age:101,
        isHappy:true,
        height:5,
        cnic:"41604-447687-9",
        email:"sameer3@gmail.com",
        gender:"Male",
        address:"Baldia Town",
        isEmployed:true,
        fatherName:"Muhammad Ameen",
        fatherIncome:20000,
        maritalStatus:"Single",
        siblings:2,
        isComingFromJob:true
    },
    {
        name:"Saim",
        contactNumber:"0300-5092789",
        education:"F.Sc",
        hasPromoCode:false,
        group:"A",
        hobbies:["Riding", "Painting", "walking"],
        age:150,
        isHappy:false,
        height:4,
        cnic:"41204-447687-9",
        email:"saim@gmail.com",
        gender:"Male",
        address:"Gulshan Iqbal",
        isEmployed:false,
        fatherName:"Muhammad Shahid",
        fatherIncome:35000,
        maritalStatus:"Single",
        siblings:8,
        isComingFromJob:false
    },
    {
        name:"Amertiya",
        contactNumber:"0345-5007000",
        education:"M.Sc",
        hasPromoCode:true,
        group:"A",
        hobbies:["Cooking", "Singing"],
        age:100,
        isHappy:true,
        height:7,
        cnic:"41204-445227-2",
        email:"arselamer@gmail.com",
        gender:"female",
        address:"Jauher",
        isEmployed:true,
        fatherName:"Ahmed Raza",
        fatherIncome:3000,
        maritalStatus:"Married",
        siblings:2,
        isComingFromJob:true
    },
    {
        name:"Armia",
        contactNumber:"0333-0908765",
        education:"B.Sc",
        hasPromoCode:true,
        group:"B",
        hobbies:"Coding",
        age:201,
        isHappy:true,
        height:4,
        cnic:"42201-225687-8",
        email:"armiakhan@gmail.com",
        gender:"female",
        address:"Garden",
        isEmployed:true,
        fatherName:"Muhammad Abid",
        fatherIncome:45000,
        maritalStatus:"Single",
        siblings:3,
        isComingFromJob:true
    },
    {
        name:"Rubab",
        contactNumber:"0333-7898900",
        education:"Matriculation",
        hasPromoCode:true,
        group:"B",
        hobbies:"Coding",
        age:201,
        isHappy:true,
        height:4,
        cnic:"41204-445777-4",
        email:"rubabjabeen@gmail.com",
        gender:"female",
        address:"Lyari",
        isEmployed:true,
        fatherName:"Yahya Khan",
        fatherIncome:15000,
        maritalStatus:"Single",
        siblings:4,
        isComingFromJob:true
    },
    {
        name:"Maha",
        contactNumber:"0343-5908705",
        education:"B.Sc",
        hasPromoCode:false,
        group:"B",
        hobbies:["Gardening", "Coding", "Cooking"],
        age:201,
        isHappy:false,
        height:4,
        cnic:"42401-445687-6",
        email:"mahashah@gmail.com",
        gender:"female",
        address:"Mai Kalachi",
        isEmployed:false,
        fatherName:"Muhammad Shuja",
        fatherIncome:30000,
        maritalStatus:"Married",
        siblings:4,
        isComingFromJob:flase
    },
    {
        name:"Sadia",
        contactNumber:"0346-1908995",
        education:"M.A",
        hasPromoCode:true,
        group:"B",
        hobbies:"Coding",
        age:201,
        isHappy:true,
        height:5,
        cnic:"41204-4453571-2",
        email:"sadiasultana3@gmail.com",
        gender:"female",
        address:"Lasbela",
        isEmployed:true,
        fatherName:"Tanveer Khan",
        fatherIncome:21000,
        maritalStatus:"Single",
        siblings:1,
        isComingFromJob:true
    },
    {
        name:"Lubna",
        contactNumber:"0300-0901769",
        education:"B.Sc",
        hasPromoCode:true,
        group:"A",
        hobbies:["Poerty", "Reading"],
        age:150,
        isHappy:false,
        height:12,
        cnic:"41204-4451687-8",
        email:"lubnakhan@gmail.com",
        gender:"female",
        address:"Guru Mander",
        isEmployed:true,
        fatherName:"Muhammad Yousuf",
        fatherIncome:30000,
        maritalStatus:"Married",
        siblings:4,
        isComingFromJob:true
    },
    {
        name:"Sarfaraz",
        contactNumber:"0343-0907775",
        education:"M.Phill",
        hasPromoCode:true,
        group:"B",
        hobbies:["Riding", "Fishing", "Drafting"],
        age:200,
        isHappy:true,
        height:5,
        cnic:"41204-445687-9",
        email:"sarfaraztwin@gmail.com",
        gender:"Male",
        address:"Shershah",
        isEmployed:false,
        fatherName:"Muhammad Ahmed",
        fatherIncome:30000,
        maritalStatus:"Single",
        siblings:7,
        isComingFromJob:false
    },
    {
        name:"Tooba",
        contactNumber:"0343-6767775",
        education:"M.Phill",
        hasPromoCode:false,
        group:"a",
        hobbies:["Riding", "Drafting"],
        age:200,
        isHappy:true,
        height:5,
        cnic:"41224-415657-6",
        email:"toobakhan@gmail.com",
        gender:"Female",
        address:"Shershah",
        isEmployed:true,
        fatherName:"Kamran Ali",
        fatherIncome:12000,
        maritalStatus:"Single",
        siblings:3,
        isComingFromJob:false
    },
    {
        name:"Faraz",
        contactNumber:"0343-0902453",
        education:"Matriculation",
        hasPromoCode:true,
        group:"B",
        hobbies:["Riding", "Coding"],
        age:46,
        isHappy:true,
        height:5,
        cnic:"42214-445687-9",
        email:"farazshah@gmail.com",
        gender:"Male",
        address:"Nazimabad",
        isEmployed:false,
        fatherName:"Muhammad Yameen",
        fatherIncome:50000,
        maritalStatus:"Single",
        siblings:2,
        isComingFromJob:false
    },
    {
        name:"Zaffar",
        contactNumber:"0343-3456715",
        education:"F.sc",
        hasPromoCode:true,
        group:"A",
        hobbies:"Coding",
        age:100,
        isHappy:true,
        height:1,
        cnic:"41204-4456789-9",
        email:"zaffarrao@gmail.com",
        gender:"Male",
        address:"North Karachi",
        isEmployed:false,
        fatherName:"Muhammad Naeem",
        fatherIncome:30000,
        maritalStatus:"Married",
        siblings:6,
        isComingFromJob:true
    },
    {
        name:"Fazal",
        contactNumber:"0316-9876543",
        education:"B.Sc",
        hasPromoCode:true,
        group:"B",
        hobbies:"Cooking",
        age:160,
        isHappy:true,
        height:5,
        cnic:"41204-345261-9",
        email:"fazal-ur-rehman@gmail.com",
        gender:"Male",
        address:"North Nazimabad",
        isEmployed:false,
        fatherName:"Nasir Khan",
        fatherIncome:25000,
        maritalStatus:"Married",
        siblings:3,
        isComingFromJob:false
    },
    {
        name:"Hina",
        contactNumber:"0343-0989076",
        education:"M.Phill",
        hasPromoCode:true,
        group:"B",
        hobbies:["Riding", "Fishing", "Drafting"],
        age:210,
        isHappy:true,
        height:5,
        cnic:"41204-4422417-6",
        email:"hinanaz@gmail.com",
        gender:"Female",
        address:"Baldia Town ",
        isEmployed:false,
        fatherName:"Muhammad Danish",
        fatherIncome:16000,
        maritalStatus:"Single",
        siblings:7,
        isComingFromJob:true
    },
    {
        name:"Saleem",
        contactNumber:"0323-0907668",
        education:"Web-Developer",
        hasPromoCode:false,
        group:"B",
        hobbies:["coding", "Drafting"],
        age:200,
        isHappy:true,
        height:5,
        cnic:"41204-445687-9",
        email:"saleemkhan@gmail.com",
        gender:"Male",
        address:"Shershah",
        isEmployed:false,
        fatherName:"Muhammad Ahmed",
        fatherIncome:30000,
        maritalStatus:"Single",
        siblings:5,
        isComingFromJob:false
    },
    {
        name:"Shabana",
        contactNumber:"0341-09087651",
        education:"M.Phill",
        hasPromoCode:true,
        group:"B",
        hobbies:["Cooking", "Designing", "Drafting"],
        age:160,
        isHappy:true,
        height:5,
        cnic:"41204-445687-4",
        email:"shabanakhan@gmail.com",
        gender:"Female",
        address:"Shershah",
        isEmployed:false,
        fatherName:"Zain",
        fatherIncome:16000,
        maritalStatus:"Married",
        siblings:2,
        isComingFromJob:false
    },
    {
        name:"Saira",
        contactNumber:"0345-5767324",
        education:"B.A",
        hasPromoCode:true,
        group:"A",
        hobbies:"Drawing",
        age:250,
        isHappy:true,
        height:3,
        cnic:"41204-443217-6",
        email:"sairakhan@gmail.com",
        gender:"Female",
        address:"Tower",
        isEmployed:false,
        fatherName:"Ibrar khan",
        fatherIncome:4000,
        maritalStatus:"Single",
        siblings:2,
        isComingFromJob:false
    },
    {
        name:"Fozia",
        contactNumber:"0333-5678943",
        education:"B.A",
        hasPromoCode:true,
        group:"A",
        hobbies:["Riding", "Fishing", "Drafting"],
        age:250,
        isHappy:true,
        height:3,
        cnic:"41204-443217-6",
        email:"foziaarshad@gmail.com",
        gender:"Female",
        address:"Tower",
        isEmployed:false,
        fatherName:"Muhammad Aamir",
        fatherIncome:45000,
        maritalStatus:"Single",
        siblings:4,
        isComingFromJob:true
    },
    {
        name:"Falak",
        contactNumber:"0456-56786943",
        education:"B.A",
        hasPromoCode:true,
        group:"A",
        hobbies:["Riding", "Drafting"],
        age:160,
        isHappy:true,
        height:4,
        cnic:"41204-443217-6",
        email:"falaknaz@gmail.com",
        gender:"Female",
        address:"Hydri",
        isEmployed:true,
        fatherName:"Muhammad Shahjahan",
        fatherIncome:6000,
        maritalStatus:"Single",
        siblings:1,
        isComingFromJob:true
    },
    {
        name:"Nida",
        contactNumber:"0333-5678943",
        education:"B.A",
        hasPromoCode:true,
        group:"A",
        hobbies:["Riding", "Fishing", "Drafting"],
        age:250,
        isHappy:true,
        height:3,
        cnic:"41456-443217-6",
        email:"nidapasha@gmail.com",
        gender:"Female",
        address:"Tower",
        isEmployed:false,
        fatherName:"Muhammad Arif",
        fatherIncome:45000,
        maritalStatus:"Married",
        siblings:3,
        isComingFromJob:true
    },
    {
        name:"Rabia",
        contactNumber:"0346-56782343",
        education:"B.Sc",
        hasPromoCode:true,
        group:"B",
        hobbies:["Reading", "Cooking", "Coding"],
        age:50,
        isHappy:false,
        height:6,
        cnic:"41446-443217-8",
        email:"rabiazahee@gmail.com",
        gender:"Female",
        address:"Liaquatabad",
        isEmployed:false,
        fatherName:"Noman",
        fatherIncome:2000,
        maritalStatus:"Single",
        siblings:2,
        isComingFromJob:true
    },
    {
        name:"Sidra",
        contactNumber:"0333-1234567",
        education:"B.A",
        hasPromoCode:true,
        group:"B",
        hobbies:["Sketching", "Drawing", "Sleeping"],
        age:50,
        isHappy:false,
        height:3,
        cnic:"41446-443217-8",
        email:"sidrakhan@gmail.com",
        gender:"Female",
        address:"PIB Colony",
        isEmployed:true,
        fatherName:"Arsalan",
        fatherIncome:30000,
        maritalStatus:"Single",
        siblings:1,
        isComingFromJob:true 
    },
    {
        name:"Somiya",
        contactNumber:"0346-2198706",
        education:"B.A",
        hasPromoCode:true,
        group:"A",
        hobbies:["Painting", "Drawing"],
        age:100,
        isHappy:false,
        height:4,
        cnic:"41446-987654-8",
        email:"somiyaansari@gmail.com",
        gender:"Female",
        address:"Orangi Town",
        isEmployed:true,
        fatherName:"Zubair",
        fatherIncome:45000,
        maritalStatus:"Married",
        siblings:1,
        isComingFromJob:false
    },
    {
        name:"Samiya",
        contactNumber:"0345-2198906",
        education:"B.A",
        hasPromoCode:false,
        group:"A",
        hobbies:"Drawing",
        age:100,
        isHappy:false,
        height:4,
        cnic:"41446-987654-8",
        email:"samiyasohail@gmail.com",
        gender:"Female",
        address:"Gulshan",
        isEmployed:true,
        fatherName:"Zakir Khan",
        fatherIncome:40000,
        maritalStatus:"Married",
        siblings:3,
        isComingFromJob:false 
    },
    {
        name:"Noman",
        contactNumber:"0345-9876543",
        education:"B.A",
        hasPromoCode:false,
        group:"B",
        hobbies:"Sleeping",
        age:101,
        isHappy:true,
        height:5,
        cnic:"33446-145354-7",
        email:"nomantweet@gmail.com",
        gender:"Male",
        address:"Sadar",
        isEmployed:true,
        fatherName:"Ashfaq Khan",
        fatherIncome:10000,
        maritalStatus:"Married",
        siblings:2,
        isComingFromJob:true 
    }
];
let whatsApp = [
    {
        name:"Aisha Khan",
        contactNumber:"0333-8009665",
        profilePicture:"https://i.ibb.co/kDJSLnb/doll-jpeg.jpg",
        readMessage:1,
        lastMessage:"will meet in class",
        status:"Seen"
    },
    {
        name:"Ammara",
        contactNumber:"0345-8669665",
        profilePicture:"https://i.ibb.co/q0pg7TP/doll2-jpeg.jpg",
        readMessage:0,
        lastMessage:"I am coming to Karachi",
        status:"Seen"  
    },
    {
        name:"Saleh",
        contactNumber:"0300-8001005",
        profilePicture:"https://i.ibb.co/MMXgHTG/flower-jpeg.jpg",
        readMessage:12,
        lastMessage:"I have selected for Tech Karo course",
        status:"Unseen"
    },
    {
        name:"Alishbah",
        contactNumber:"0346-2334965",
        profilePicture:"https://i.ibb.co/fv02Jw1/ship-jpeg.jpg",
        readMessage:"All",
        lastMessage:"Pay my regards to all",
        status:"Seen"
    },
    {
        name:"Alina",
        contactNumber:"0300-6765431",
        profilePicture:"https://i.ibb.co/pvmWFSY/horse-jpeg.jpg",
        readMessage:"All",
        lastMessage:"Good Night",
        status:"Seen"
    },
    {
        name:"Danish",
        contactNumber:"0346-8009860",
        profilePicture:"https://i.ibb.co/jDpc5FG/mobile-jpeg.jpg",
        readMessage:2,
        lastMessage:"Barish horhe hy hlki hlki",
        status:"Seen"
    }
];